### ISSUE TITLE
Check for chroot and nhscripts

### ISSUE THREAD

**Issue by jcadduono** [jmingov/NetHunter-Terminal-Emulator#1]
We should probably check for the existence of, in order, when using Kali option:

(symlink exists)
```sh
if [ ! -L "/system/bin/bootkali_login" ]; then
```
alert user that system symlinks are not installed (reinstall nethunter)

(actual script link points to exists)
```sh
if ! readlink -q "/system/bin/bootkali_login" >/dev/null; then
```
alert user to open nethunter app to complete installation (offer to open nethunter app)

(chroot is installed)
```sh
kalifs=(/data/local/nhsystem/kali-*)
if [ ! -d "${kalifs[0]}" ]; then
```
alert user that chroot is not installed (offer to open nethunter app)

I suppose there might be better ways to implement this in java (I dunno how to work that voodoo magic) so I'll just leave this issue here. ;)

As it is now there are plenty of users opening tickets because of this (terminal crashes when selecting kali)

**Comment by jmingov** [comment]
Yeah, we moved this to binkybear´s repo.
